package com.example.windqq.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.windqq.bean.DaoCallBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "calls".
*/
public class DaoCallBeanDao extends AbstractDao<DaoCallBean, Long> {

    public static final String TABLENAME = "calls";

    /**
     * Properties of entity DaoCallBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User = new Property(1, String.class, "user", false, "USER");
        public final static Property Touserid = new Property(2, String.class, "touserid", false, "TOUSERID");
        public final static Property Fromuserid = new Property(3, String.class, "fromuserid", false, "FROMUSERID");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property Type = new Property(5, int.class, "type", false, "TYPE");
        public final static Property Time = new Property(6, long.class, "time", false, "TIME");
    }


    public DaoCallBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DaoCallBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"calls\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER\" TEXT NOT NULL UNIQUE ," + // 1: user
                "\"TOUSERID\" TEXT UNIQUE ," + // 2: touserid
                "\"FROMUSERID\" TEXT," + // 3: fromuserid
                "\"CONTENT\" TEXT," + // 4: content
                "\"TYPE\" INTEGER NOT NULL ," + // 5: type
                "\"TIME\" INTEGER NOT NULL );"); // 6: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"calls\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DaoCallBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUser());
 
        String touserid = entity.getTouserid();
        if (touserid != null) {
            stmt.bindString(3, touserid);
        }
 
        String fromuserid = entity.getFromuserid();
        if (fromuserid != null) {
            stmt.bindString(4, fromuserid);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
        stmt.bindLong(6, entity.getType());
        stmt.bindLong(7, entity.getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DaoCallBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUser());
 
        String touserid = entity.getTouserid();
        if (touserid != null) {
            stmt.bindString(3, touserid);
        }
 
        String fromuserid = entity.getFromuserid();
        if (fromuserid != null) {
            stmt.bindString(4, fromuserid);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
        stmt.bindLong(6, entity.getType());
        stmt.bindLong(7, entity.getTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DaoCallBean readEntity(Cursor cursor, int offset) {
        DaoCallBean entity = new DaoCallBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // user
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // touserid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fromuserid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // content
            cursor.getInt(offset + 5), // type
            cursor.getLong(offset + 6) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DaoCallBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser(cursor.getString(offset + 1));
        entity.setTouserid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFromuserid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.getInt(offset + 5));
        entity.setTime(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DaoCallBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DaoCallBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DaoCallBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
