package com.example.wanandroid.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wanandroid.bean.LikeDaoBean;

import com.example.wanandroid.dao.LikeDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likeDaoBeanDaoConfig;

    private final LikeDaoBeanDao likeDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likeDaoBeanDaoConfig = daoConfigMap.get(LikeDaoBeanDao.class).clone();
        likeDaoBeanDaoConfig.initIdentityScope(type);

        likeDaoBeanDao = new LikeDaoBeanDao(likeDaoBeanDaoConfig, this);

        registerDao(LikeDaoBean.class, likeDaoBeanDao);
    }
    
    public void clear() {
        likeDaoBeanDaoConfig.clearIdentityScope();
    }

    public LikeDaoBeanDao getLikeDaoBeanDao() {
        return likeDaoBeanDao;
    }

}
